[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = ["npm install -g pnpm && pnpm install"]

[phases.build]
cmds = ["BASE_PATH=/ pnpm --filter @workspace/firebox run build && pnpm --filter @workspace/api-server run build"]

[start]
cmd = "node artifacts/api-server/dist/index.mjs"
